portada:
  pattern: /{ciudad}
  defaults: {_controller:OfertaBundle:Default:portada, ciudad: null}
 
_portada:
  pattern: /
  defaults: {_controller:OfertaBundle:Default:portada}
  
ciudad_cambiar:
  pattern: /ciudad/cambiar-a-{ciudad}
  defaults: {_controller: CiudadBundle:Default:cambiar}
  
UsuarioBundle:
    resource: "@UsuarioBundle/Resources/config/routing.yml"
    prefix:   /

TiendaBundle:
    resource: "@TiendaBundle/Resources/config/routing.yml"
    prefix:   /

CiudadBundle:
    resource: "@CiudadBundle/Resources/config/routing.yml"
    prefix:   /

OfertaBundle:
    resource: "@OfertaBundle/Resources/config/routing.yml"
    prefix:   /

pagina_estatica:
   pattern: /sitio/{pagina}/
   defaults: { _controller: OfertaBundle:Sitio:estatica}

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
